Internal Server Error: /api-auth/login
"POST /api-auth/login HTTP/1.1" 500 58
Internal Server Error: /api-auth/login
"POST /api-auth/login HTTP/1.1" 500 58
Internal Server Error: /api-auth/login
"POST /api-auth/login HTTP/1.1" 500 58
Internal Server Error: /api-auth/login
"POST /api-auth/login HTTP/1.1" 500 58
Internal Server Error: /api-auth/login
"POST /api-auth/login HTTP/1.1" 500 58
Internal Server Error: /api-auth/login
"POST /api-auth/login HTTP/1.1" 500 58
Internal Server Error: /api/menu/items/
Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'New Capital'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/graduationProject_ITI/backend/menu/views.py", line 48, in get_queryset
    queryset = queryset.filter(branch=self.request.user.branch)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'New Capital'.
"GET /api/menu/items/ HTTP/1.1" 500 169917
Internal Server Error: /api/menu/items/
Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'New Capital'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/graduationProject_ITI/backend/menu/views.py", line 48, in get_queryset
    queryset = queryset.filter(branch=self.request.user.branch)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'New Capital'.
"GET /api/menu/items/ HTTP/1.1" 500 169917
Internal Server Error: /api/menu/items/
Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'New Capital'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/graduationProject_ITI/backend/menu/views.py", line 48, in get_queryset
    queryset = queryset.filter(branch=self.request.user.branch)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'New Capital'.
"GET /api/menu/items/ HTTP/1.1" 500 169917
Internal Server Error: /api/menu/items/
Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'New Capital'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/graduationProject_ITI/backend/menu/views.py", line 48, in get_queryset
    queryset = queryset.filter(branch=self.request.user.branch)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'New Capital'.
"GET /api/menu/items/ HTTP/1.1" 500 169917
Internal Server Error: /api/menu/items/
Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'New Capital'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/graduationProject_ITI/backend/menu/views.py", line 48, in get_queryset
    queryset = queryset.filter(branch=self.request.user.branch)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'New Capital'.
"GET /api/menu/items/ HTTP/1.1" 500 168594
Internal Server Error: /api/menu/items/
Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'New Capital'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/graduationProject_ITI/backend/menu/views.py", line 48, in get_queryset
    queryset = queryset.filter(branch=self.request.user.branch)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'New Capital'.
"GET /api/menu/items/ HTTP/1.1" 500 169917
Internal Server Error: /api/menu/items/
Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'New Capital'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/graduationProject_ITI/backend/menu/views.py", line 48, in get_queryset
    queryset = queryset.filter(branch=self.request.user.branch)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'New Capital'.
"GET /api/menu/items/ HTTP/1.1" 500 169917
Internal Server Error: /api/menu/items/
Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'New Capital'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/graduationProject_ITI/backend/menu/views.py", line 48, in get_queryset
    queryset = queryset.filter(branch=self.request.user.branch)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'New Capital'.
"GET /api/menu/items/ HTTP/1.1" 500 169917
Internal Server Error: /api/menu/items/
Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'New Capital'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/graduationProject_ITI/backend/menu/views.py", line 48, in get_queryset
    queryset = queryset.filter(branch=self.request.user.branch)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'New Capital'.
"GET /api/menu/items/ HTTP/1.1" 500 168594
Internal Server Error: /api/menu/items/
Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'New Capital'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/graduationProject_ITI/backend/menu/views.py", line 48, in get_queryset
    queryset = queryset.filter(branch=self.request.user.branch)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'New Capital'.
"GET /api/menu/items/ HTTP/1.1" 500 168594
Internal Server Error: /api/menu/items/
Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'New Capital'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/graduationProject_ITI/backend/menu/views.py", line 50, in get_queryset
    queryset = queryset.filter(branch=self.request.user.branch)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'New Capital'.
"GET /api/menu/items/ HTTP/1.1" 500 169917
Internal Server Error: /api/menu/items/
Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'New Capital'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/graduationProject_ITI/backend/menu/views.py", line 50, in get_queryset
    queryset = queryset.filter(branch=self.request.user.branch)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'New Capital'.
"GET /api/menu/items/ HTTP/1.1" 500 169917
Internal Server Error: /api/menu/items/
Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/graduationProject_ITI/backend/menu/views.py", line 50, in get_queryset
    queryset = queryset.filter(branch=self.request.user.branch)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AnonymousUser' object has no attribute 'branch'
"GET /api/menu/items/ HTTP/1.1" 500 113967
Internal Server Error: /api/menu/items/
Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/graduationProject_ITI/backend/menu/views.py", line 50, in get_queryset
    queryset = queryset.filter(branch=self.request.user.branch)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AnonymousUser' object has no attribute 'branch'
"GET /api/menu/items/ HTTP/1.1" 500 113967
Internal Server Error: /api/menu/items/
Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'New Capital'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/graduationProject_ITI/backend/menu/views.py", line 50, in get_queryset
    queryset = queryset.filter(branch=self.request.user.branch)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'New Capital'.
"GET /api/menu/items/ HTTP/1.1" 500 169917
Internal Server Error: /api/menu/items/
Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'New Capital'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/graduationProject_ITI/backend/menu/views.py", line 50, in get_queryset
    queryset = queryset.filter(branch=self.request.user.branch)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'New Capital'.
"GET /api/menu/items/ HTTP/1.1" 500 169917
Internal Server Error: /api/menu/items/
Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'New Capital'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/graduationProject_ITI/backend/menu/views.py", line 50, in get_queryset
    queryset = queryset.filter(branch=self.request.user.branch)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'New Capital'.
"GET /api/menu/items/ HTTP/1.1" 500 169917
Internal Server Error: /api/menu/items/
Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'New Capital'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/graduationProject_ITI/backend/menu/views.py", line 50, in get_queryset
    queryset = queryset.filter(branch=self.request.user.branch)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'New Capital'.
"GET /api/menu/items/ HTTP/1.1" 500 169917
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 40
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 40
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 40
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 40
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 40
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 40
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 40
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 40
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 40
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 40
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 40
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 40
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 40
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 40
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 40
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 40
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 40
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 40
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 40
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 63
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 63
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 63
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 63
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 63
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 63
Internal Server Error: /api/menu/items/
Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "users_user" does not exist
LINE 1: ...er"."date_joined", "users_user"."last_login" FROM "users_use...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/request.py", line 231, in user
    self._authenticate()
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/request.py", line 384, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework_simplejwt/authentication.py", line 51, in authenticate
    return self.get_user(validated_token), validated_token
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework_simplejwt/authentication.py", line 130, in get_user
    user = self.user_model.objects.get(**{api_settings.USER_ID_FIELD: user_id})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "users_user" does not exist
LINE 1: ...er"."date_joined", "users_user"."last_login" FROM "users_use...
                                                             ^

"GET /api/menu/items/ HTTP/1.1" 500 200781
Internal Server Error: /api/menu/items/
Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "users_user" does not exist
LINE 1: ...er"."date_joined", "users_user"."last_login" FROM "users_use...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/request.py", line 231, in user
    self._authenticate()
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework/request.py", line 384, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework_simplejwt/authentication.py", line 51, in authenticate
    return self.get_user(validated_token), validated_token
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/rest_framework_simplejwt/authentication.py", line 130, in get_user
    user = self.user_model.objects.get(**{api_settings.USER_ID_FIELD: user_id})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/abougabal/.local/share/virtualenvs/iti_cafe-C5NSXt1u/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "users_user" does not exist
LINE 1: ...er"."date_joined", "users_user"."last_login" FROM "users_use...
                                                             ^

"GET /api/menu/items/ HTTP/1.1" 500 200781
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
Internal Server Error: /api/menu/items/
"GET /api/menu/items/ HTTP/1.1" 500 65
